name: GH Pages

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# permissions:
#   contents: write

# start getting duplicate gardenEntry?
# permissions:
#   contents: read
#   pages: write
#   id-token: write

# concurrency:
#   group: "pages"
#   cancel-in-progress: false

# end

# concurrency:
#   group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  build:
  
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
#      - run: npm install
 #     - run: npm run build --if-present

      - run: npm install  # Add verbose logging for npm install
      - run: npm run build --verbose  # Add verbose logging for npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.DG_TOKEN }}  
          publish_dir: ./dist
